-- forgetuser
SELECT
    USUR_NICKNAME
FROM
    PERSONA
    INNER JOIN USUARIO ON USUARIO.USUR_ID_USUARIO = PERSONA.USUR_ID_USUARIO
WHERE
    PERS_DNI = 1006458608
LIMIT
    1;


--login
SELECT
    USUARIO.USUR_NICKNAME,
    ROL.ROLL_NOMBREROL
FROM
    USUARIO
    INNER JOIN ROL on USUARIO.ROLL_ID_ROL = ROL.ROLL_ID_ROL
WHERE
    USUARIO.USUR_NICKNAME = ?
    AND USUARIO.USUR_PASSWORD = ?
ORDER BY
    USUARIO.USUR_ID_USUARIO ASC;