INSERT INTO ROL  (ROLL_ID_ROL, ROLL_NOMBREROL) VALUES 
    (1,'ESTUDIANTE'),
    (2,'ADMINISTRATIVO'),
    (3,'DOCENTE'),
    (4,'EGRESADO'),
    (5,'Encargado'),
    (6,'AUXILIAR');

INSERT INTO PERSONA (PERS_ID_PERSONA, PERS_NOMBRE1, PERS_NOMBRE2, PERS_APELLIDO1, PERS_APELLIDO2, USUR_ID_USUARIO) VALUES 
    (1,'JOSE','DANIEL','TOQUICA','AGUDELO',1),
    (2,'YERSON','ARLEY','CENON','CABRERA',2),
    (3,'JULIAN',NULL,'CHINGAL',NULL,3),
    (4,'ANGIE','ALEXANDRA','ORTIZ','PALACIOS',4),
    (5,'FALCAO',NULL,'GARCIA',NULL,1);
    

INSERT INTO USUARIO (USUR_ID_USUARIO, USUR_NICKNAME, USUR_PASSWORD, ROLL_ID_ROL) VALUES
    (1,'J.TOQUICA','12345',1),
    (2,'Y.CENON','12345',2),
    (3,'J.CHINGAL','12345',3),
    (4,'A.ORTIZ','12345',4),
    (5,'F.GARCIA','12345',1);

