
CREATE TABLE PERSONA (
    PERS_ID_PERSONA int(11) NOT NULL,
    PERS_DNI int(11) NOT NULL,
    PERS_NOMBRE1 varchar(50) NOT NULL,
    PERS_NOMBRE2 varchar(50) DEFAULT NULL,
    PERS_APELLIDO1 varchar(60) NOT NULL,
    PERS_APELLIDO2 varchar(60) DEFAULT NULL,
    PERS_GENERO varchar(20) NOT NULL,
    PERS_CORREO varchar(150) NOT NULL,
    USUR_ID_USUARIO int(11) NOT NULL,
    TIID_ID_TIPOID int(11) NOT NULL
);

CREATE TABLE TIPOIDENTIFICACION (
    TIID_ID_TIPOID int(11) NOT NULL,
    TIID_NOMBRE_TIPOID varchar(50) NOT NULL
);

CREATE TABLE USUARIO (
    USUR_ID_USUARIO int(11) NOT NULL,
    USUR_NICKNAME varchar(100) NOT NULL,
    USUR_PASSWORD varchar(100) NOT NULL,
    FOTO_IDFOTO INT
);

CREATE TABLE ROL (
    ROLL_ID_ROL int(11) NOT NULL,
    ROLL_NOMBREROL varchar(50) NOT NULL
);

CREATE TABLE ROLUSUARIO (
    ROUS_IDROLUSURARIO INT NOT NULL,
    ROLL_ID_ROL int(11) NOT NULL,
    USUR_ID_USUARIO int(11) NOT NULL,
    ROUS_ESTADO VARCHAR(15) NOT NULL
);

------------------------------------------------------------------------------------
CREATE TABLE TIPORECURSOFISICO (
  TIRE_IDTIPORECURSOFISICO INT NOT NULL,
  TIRE_NOMBRETIPORECURSOFISICO VARCHAR(45) NOT NULL
);

CREATE TABLE INVENTARIO (
  INVE_IDINVENTARIO INT NOT NULL,
  INVE_NOMBREINVENTARIO VARCHAR(45) NOT NULL
);

CREATE TABLE ESTADOSOLICITUD (
  ESSO_IDESTADOSOLICITUD INT NOT NULL,
  ESSO_NOMBREESTADOSOLICITUD VARCHAR(45) NOT NULL
);

CREATE TABLE DETALLEELEMENTO (
  DEEL_IDDETALLEELEMENTO INT NOT NULL,
  DEEL_FECHAREGISTRO VARCHAR(45) NOT NULL,
  DEEL_DESCRIPCION VARCHAR(45) NOT NULL,
  DEEL_IMAGEN INT NOT NULL
);

CREATE TABLE RESCURSOFISICO (
  REFI_IDRESCURSOFISICO INT NULL,
  REFI_NOMBRERESCURSOFISICO VARCHAR(45) NOT NULL,
  REFI_CAPACIDADRECURSOFISICO INT NOT NULL,
  REFI_ESTADORECURSOFISICO VARCHAR(45) NOT NULL,
  FK_TIRE_IDTIPORECURSOFISICO INT NOT NULL,
  FK_INVE_IDINVENTARIO INT NOT NULL
);

CREATE TABLE GRUPOCURSO (
  GRCU_IDGRUPOCURSO INT NOT NULL,
  GRCU_NOMBREGRUPOCURSO VARCHAR(45) NOT NULL,
  GRCU_DOCENTEGRUPOCURSO VARCHAR(45) NOT NULL,
  GRDO_CANTIDADESTUDIANTES INT NOT NULL,
  FK_REFI_IDRESCURSOFISICO INT NOT NULL
);

CREATE TABLE SOLICITUD (
  SOLI_IDSOLICITUD INT NOT NULL,
  SOLI_ESTADOSOLICITUD VARCHAR(45) NOT NULL,
  SOLI_FECHASOLICITUD DATETIME NOT NULL,
  SOLI_FECHADEVOLUCION DATETIME NOT NULL,
  SOLI_FECHAPRESTAMO DATETIME NOT NULL,
  SOLI_DESCRIPCION VARCHAR(45) NULL,
  ARCH_IDARCHIVOSOLICITUD INT NULL,
  FK_ROUS_IDROLUSUARIO INT NOT NULL,
  FK_ESSO_IDESTADOSOLICITUD INT NOT NULL,
  FK_REFI_IDRESCURSOFISICO INT NOT NULL,
  INVENTARIO_INVE_IDINVENTARIO INT NOT NULL
);

CREATE TABLE ELEMENTOS (
  ELEM_IDELEMENTO INT NOT NULL,
  ELEM_NOMBREELEMENTO VARCHAR(45) NOT NULL,
  ELEM_MARCA VARCHAR(45) NOT NULL,
  ELEM_ESTADO VARCHAR(45) NOT NULL,
  FK_DEEL_IDDETALLEELEMENTO INT NOT NULL
);

CREATE TABLE PRESTAMO (
  PRES_IDPRESTAMO INT NOT NULL,
  PRES_FECHAPRESTAMO DATETIME NOT NULL,
  PRES_FECHADEVOLUCION DATETIME NOT NULL,
  ESTADO VARCHAR(45) NOT NULL,
  FK_USUR_IDUSUARIO INT NOT NULL,
  FK_PROD_IDPRODUCTO INT NOT NULL
);

CREATE TABLE CATEGORIA (
  CATE_IDCATEGORIA INT NOT NULL,
  CATE_NOMBRECATEGORIA VARCHAR(45) NOT NULL,
  FK_ELEM_IDELEMENTO INT NOT NULL,
  FK_INVE_IDINVENTARIO INT NOT NULL
);


-- PRIMARY KEYS
ALTER Table
    PERSONA
ADD CONSTRAINT pk_id_persona PRIMARY KEY (PERS_ID_PERSONA);
ALTER Table
    TIPOIDENTIFICACION
ADD CONSTRAINT pk_id_tipo PRIMARY KEY (TIID_ID_TIPOID);

ALTER Table
    USUARIO
ADD CONSTRAINT pk_id_usuario PRIMARY KEY (USUR_ID_USUARIO);

ALTER Table
    ROL
ADD CONSTRAINT pk_id_rol PRIMARY KEY (ROLL_ID_ROL);

ALTER TABLE
    ROLUSUARIO
ADD CONSTRAINT pk_id_usuariorol PRIMARY KEY (ROUS_IDROLUSURARIO, USUR_ID_USUARIO, ROLL_ID_ROL);
------------------------------------------------------------------------------------
ALTER TABLE TIPORECURSOFISICO ADD CONSTRAINT pk_tipoid PRIMARY KEY (TIRE_IDTIPORECURSOFISICO);
ALTER TABLE INVENTARIO ADD CONSTRAINT pk_inventario PRIMARY KEY (INVE_IDINVENTARIO);
ALTER TABLE ESTADOSOLICITUD ADD CONSTRAINT pk_ESTADOSOLICITUD PRIMARY KEY (ESSO_IDESTADOSOLICITUD);
ALTER TABLE DETALLEELEMENTO ADD CONSTRAINT pk_DETALLEELEMENTO PRIMARY KEY (DEEL_IDDETALLEELEMENTO);
ALTER TABLE RESCURSOFISICO ADD CONSTRAINT pk_RESCURSOFISICO PRIMARY KEY (REFI_IDRESCURSOFISICO, FK_INVE_IDINVENTARIO, FK_TIRE_IDTIPORECURSOFISICO);
ALTER TABLE GRUPOCURSO ADD CONSTRAINT pk_GRUPOCURSO PRIMARY KEY (GRCU_IDGRUPOCURSO, FK_REFI_IDRESCURSOFISICO);
ALTER TABLE SOLICITUD ADD CONSTRAINT pk_SOLICITUD PRIMARY KEY (SOLI_IDSOLICITUD, FK_ROUS_IDROLUSUARIO, FK_ESSO_IDESTADOSOLICITUD, FK_REFI_IDRESCURSOFISICO, INVENTARIO_INVE_IDINVENTARIO);
ALTER TABLE PRESTAMO ADD CONSTRAINT pk_PRESTAMO PRIMARY KEY (PRES_IDPRESTAMO, FK_USUR_IDUSUARIO, FK_PROD_IDPRODUCTO);
ALTER TABLE CATEGORIA ADD CONSTRAINT pk_CATEGORIA PRIMARY KEY (CATE_IDCATEGORIA, FK_ELEM_IDELEMENTO, FK_INVE_IDINVENTARIO);
ALTER TABLE ELEMENTOS ADD CONSTRAINT pk_ELEMENTOS PRIMARY KEY (ELEM_IDELEMENTO, FK_DEEL_IDDETALLEELEMENTO);

-- FOREIGN KEY
ALTER Table
    PERSONA
ADD CONSTRAINT fk_USUR_ID_USUARIO FOREIGN KEY (USUR_ID_USUARIO) REFERENCES USUARIO (USUR_ID_USUARIO) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER Table
    PERSONA
ADD CONSTRAINT fk_tipoid FOREIGN KEY (TIID_ID_TIPOID) REFERENCES TIPOIDENTIFICACION (TIID_ID_TIPOID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    ROLUSUARIO
ADD CONSTRAINT fk_rol FOREIGN KEY (ROLL_ID_ROL) REFERENCES ROL (ROLL_ID_ROL) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    ROLUSUARIO
ADD CONSTRAINT fk_usuario FOREIGN KEY (USUR_ID_USUARIO) REFERENCES USUARIO (USUR_ID_USUARIO) ON DELETE NO ACTION ON UPDATE NO ACTION;


-------------------------------------------------------------------------
ALTER TABLE
    GRUPOCURSO
ADD CONSTRAINT fk_RECURSOgru FOREIGN KEY (FK_REFI_IDRESCURSOFISICO) REFERENCES RESCURSOFISICO (REFI_IDRESCURSOFISICO) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    RESCURSOFISICO
ADD CONSTRAINT fk_tiporecursorecur FOREIGN KEY (FK_TIRE_IDTIPORECURSOFISICO) REFERENCES TIPORECURSOFISICO (TIRE_IDTIPORECURSOFISICO) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    RESCURSOFISICO
ADD CONSTRAINT fk_inventariores FOREIGN KEY (FK_INVE_IDINVENTARIO) REFERENCES INVENTARIO (INVE_IDINVENTARIO) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    CATEGORIA
ADD CONSTRAINT fk_id_elementocateg FOREIGN KEY (FK_ELEM_IDELEMENTO) REFERENCES ELEMENTOS (ELEM_IDELEMENTO) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    CATEGORIA
ADD CONSTRAINT fk_id_inventariocat FOREIGN KEY (FK_INVE_IDINVENTARIO) REFERENCES INVENTARIO (INVE_IDINVENTARIO) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    ELEMENTOS
ADD CONSTRAINT fk_id_ielementos FOREIGN KEY (FK_DEEL_IDDETALLEELEMENTO) REFERENCES DETALLEELEMENTO (DEEL_IDDETALLEELEMENTO) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    PRESTAMO
ADD CONSTRAINT fk_id_usuariopres FOREIGN KEY (FK_USUR_IDUSUARIO) REFERENCES USUARIO (USUR_ID_USUARIO) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    PRESTAMO
ADD CONSTRAINT FK_PROD_IDPRODUCTO FOREIGN KEY (FK_PROD_IDPRODUCTO) REFERENCES ELEMENTOS (ELEM_IDELEMENTO) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    SOLICITUD
ADD CONSTRAINT FK_ROUS_IDROLUSUARIO FOREIGN KEY (FK_ROUS_IDROLUSUARIO) REFERENCES USUARIO (USUR_ID_USUARIO) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    SOLICITUD
ADD CONSTRAINT FK_ESSO_IDESTADOSOLICITUD FOREIGN KEY (FK_ESSO_IDESTADOSOLICITUD) REFERENCES ESTADOSOLICITUD (ESSO_IDESTADOSOLICITUD) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    SOLICITUD
ADD CONSTRAINT FK_REFI_IDRESCURSOFISICO FOREIGN KEY (FK_REFI_IDRESCURSOFISICO) REFERENCES RESCURSOFISICO (REFI_IDRESCURSOFISICO) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    SOLICITUD
ADD CONSTRAINT INVENTARIO_INVE_IDINVENTARIO FOREIGN KEY (INVENTARIO_INVE_IDINVENTARIO) REFERENCES INVENTARIO (INVE_IDINVENTARIO) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE
    SOLICITUD
ADD CONSTRAINT INVENTARIO_INVE_IDINVENTARIO FOREIGN KEY (INVENTARIO_INVE_IDINVENTARIO) REFERENCES INVENTARIO (INVE_IDINVENTARIO) ON DELETE NO ACTION ON UPDATE NO ACTION;



