DELIMITER //
CREATE PROCEDURE FILTROCAPACIDAD(IN Capacidad INT)
BEGIN
    SELECT
        REFI_IDRESCURSOFISICO,
        REFI_NOMBRERESCURSOFISICO,
        REFI_CAPACIDADRECURSOFISICO,
        REFI_ESTADORECURSOFISICO
    FROM
        RESCURSOFISICO
    WHERE
        REFI_CAPACIDADRECURSOFISICO <= Capacidad;
END;

DELIMITER;


CALL FILTROCAPACIDAD(200);

SELECT * FROM FILTROCAPACIDAD;